language: python

python:
- 3.7

dist: xenial

sudo: true

addons:
  apt_packages:
  - libcups2-dev
services:
- mysql
install:
  - pip install -U pip coverage flake8 tox-travis
before_script:
- flake8 ambition_visit_schedule
- mysql -e 'create database edc character set utf8;'
script:
- coverage run -m tox
after_success:
  - coveralls
